services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15-oss
    container_name: timescaledb_service
    ports:
      - "${PG_PORT_HOST}:${PG_PORT_CONTAINER}" # e.g., 5433:5432, defined in .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - sentiment_net

  reddit_scraper:
    build:
      context: ./reddit_scraper
      dockerfile: Dockerfile
    container_name: reddit_scraper_service
    depends_on:
      timescaledb:
        condition: service_healthy # Or simply service_started if healthcheck not defined for timescaledb
    env_file:
      - ./scraper.env # Ensure this file is created from scraper.env.example
    volumes:
      - ./reddit_scraper:/app/reddit_scraper # For development: mounts local code into container
      - ./scraper_logs:/app/logs
    networks:
      - sentiment_net
    # The Dockerfile's ENTRYPOINT and CMD will be used unless overridden here

volumes:
  timescaledb_data:

networks:
  sentiment_net:
    driver: bridge
