services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15-oss
    container_name: timescaledb_service
    ports:
      - "${PG_PORT_HOST}:${PG_PORT_CONTAINER}" # e.g., 5433:5432, defined in .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - sentiment_net
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB} -h localhost -p ${PG_PORT_CONTAINER}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

  reddit_scraper:
    build:
      context: .
      dockerfile: ./reddit_scraper/Dockerfile
    container_name: reddit_scraper_service
    depends_on:
      timescaledb:
        condition: service_healthy # Or simply service_started if healthcheck not defined for timescaledb
    env_file:
      - ./scraper.env # Ensure this file is created from scraper.env.example
    volumes:
      - ./reddit_scraper:/app/reddit_scraper # Mounts the host's reddit_scraper dir to /app/reddit_scraper
      - ./reddit_scraper/config.yaml:/app/config.yaml # Explicitly mount config.yaml
      - ./scraper_logs:/app/logs
      - ./data:/app/data  # Persist CSV data on host
    networks:
      - sentiment_net
    # The Dockerfile's ENTRYPOINT and CMD will be used unless overridden here

  sentiment_analyzer:
    build:
      context: .
      dockerfile: ./sentiment_analyzer/Dockerfile
    container_name: sentiment_analyzer_service
    depends_on:
      timescaledb:
        condition: service_healthy
    env_file:
      - ./.env
    # Enable GPU access (NVIDIA Container Runtime required on host)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_NAME=${PG_DB}
      - ALEMBIC_DATABASE_URL=postgresql+psycopg://${PG_USER}:${PG_PASSWORD}@timescaledb:5432/${PG_DB}
      - DB_URL_ASYNC=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@timescaledb:5432/${PG_DB}
      - DATABASE_URL=postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@timescaledb:5432/${PG_DB}
      # GPU-related env vars (the runtime will honour these)
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./sentiment_analyzer:/app/sentiment_analyzer
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    networks:
      - sentiment_net
    restart: unless-stopped

volumes:
  timescaledb_data:

networks:
  sentiment_net:
    driver: bridge
