"""add_processed_at_and_index_to_raw_events_for_sentiment

Revision ID: 84df3802d234
Revises: d2dff1ec4c53
Create Date: 2025-06-06 22:07:42.571190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84df3802d234'
down_revision: Union[str, None] = 'd2dff1ec4c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_events',
                  sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp when sentiment analysis was completed for this event')
    )
    op.create_index('ix_raw_events_processed_occurred_at',
                    'raw_events',
                    ['processed', 'occurred_at'],
                    unique=False,
                    postgresql_where=sa.text('processed = FALSE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_events_processed_occurred_at', table_name='raw_events')
    op.drop_column('raw_events', 'processed_at')
    # ### end Alembic commands ###
