version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    format: "%(asctime)s %(name)s %(levelname)s %(module)s %(funcName)s %(lineno)d %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  console_json:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: sentiment_analyzer.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

  file_json_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: sentiment_analyzer_json.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  uvicorn.error:
    level: INFO
    handlers: [console] # or [console_json] based on preference
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [console] # or [console_json] based on preference
    propagate: no
  fastapi:
    level: INFO
    handlers: [console] # or [console_json] based on preference
    propagate: no
  sqlalchemy.engine:
    level: WARNING # Set to INFO to see SQL queries
    handlers: [console]
    propagate: no
  alembic:
    level: INFO
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console, file_handler] # Default to console and file_handler
  # To use JSON logging by default, change to:
  # handlers: [console_json, file_json_handler]
